### ISSUE TITLE
No module named AppKit

### ISSUE THREAD

**Issue by sepehr** [fniephaus/alfred-dropbox#4]
When no auth token is set: 

![screen shot 2017-04-23 at 6 12 08 pm](https://cloud.githubusercontent.com/assets/23576/25314012/713e9040-2850-11e7-89d9-235b665311cd.png)

The workflow throws an exception:

```
Starting debug for 'Dropbox for Alfred'

[2017-04-23 18:07:14][STDERR: input.scriptfilter] Workflow version : 2.1.0
The debug log can be found in the log file:
/Users/Sepehr/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.044 seconds.
[2017-04-23 18:07:15][STDERR: input.scriptfilter] Workflow version : 2.1.0
The debug log can be found in the log file:
/Users/Sepehr/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.061 seconds.
[2017-04-23 18:07:21][ERROR: action.script] Traceback (most recent call last):
  File "dropbox_handler.py", line 5, in <module>
    from AppKit import NSPasteboard, NSArray
ImportError: No module named AppKit
[2017-04-23 18:08:18][STDERR: input.scriptfilter] Workflow version : 2.1.0
The debug log can be found in the log file:
/Users/Sepehr/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.078 seconds.
[2017-04-23 18:09:42][STDERR: input.scriptfilter] Workflow version : 2.1.0
The debug log can be found in the log file:
/Users/Sepehr/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.066 seconds.
[2017-04-23 18:09:44][STDERR: input.scriptfilter] Workflow version : 2.1.0
The debug log can be found in the log file:
/Users/Sepehr/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/com.fniephaus.dropbox.log
Workflow finished in 0.062 seconds.
[2017-04-23 18:09:59][ERROR: action.script] Traceback (most recent call last):
  File "dropbox_handler.py", line 5, in <module>
    from AppKit import NSPasteboard, NSArray
ImportError: No module named AppKit
```

**Comment by sepehr** [comment]
Thanks for the quick fix :)
