### ISSUE TITLE
API Issue, auth went fine next step failed

### ISSUE THREAD

**Issue by unsalted** [fniephaus/alfred-dropbox#7]
```
[2018-06-13 11:24:21][ERROR: input.scriptfilter] Code 1: 11:24:21 workflow.py:2249 DEBUG    workflow version: 2.3.0
11:24:21 workflow.py:1657 DEBUG    reading settings from /Users/x/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json
11:24:21 workflow.py:2532 DEBUG    Update check not due
11:24:21 workflow.py:1884 DEBUG    loading cached data: /Users/x/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
11:24:21 workflow.py:2462 DEBUG    update_data: {u'available': False}
11:24:21 workflow.py:2651 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
11:24:21 workflow.py:2651 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
11:24:21 workflow.py:2267 ERROR    [400] u'v1_retired'
Traceback (most recent call last):
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/workflow/workflow.py", line 2260, in run
    func(self)
  File "dropbox_filter.py", line 28, in main
    'dropbox_accounts', data_func=get_account_info, max_age=360)
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/helpers.py", line 40, in get_account_info
    output.append(api_client.account_info())
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/dropbox/client.py", line 149, in account_info
    return self.rest_client.GET(url, headers)
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/dropbox/rest.py", line 311, in GET
    return cls.IMPL.GET(*n, **kw)
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/dropbox/rest.py", line 246, in GET
    return self.request("GET", url, headers=headers, raw_response=raw_response)
  File "/Users/x/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.0A1B5C13-ED4A-401B-ACB3-CDC92AE4DDFE/dropbox/rest.py", line 227, in request
    raise ErrorResponse(r, r.read())
ErrorResponse: [400] u'v1_retired'
11:24:21 workflow.py:2269 INFO     for assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
11:24:21 workflow.py:2290 DEBUG    workflow finished in 0.229 seconds
```

**Comment by fniephaus** [comment]
Hi @unsalted,
The workflow still uses Dropbox's API v1 which was deprecated a while ago but still worked for some reason. I've started to work on v2 support (see `dev` branch), but it's not quite ready yet. I'm afraid I don't have much time to work on this at the moment. Contributions are welcome!

**Comment by davidvb** [comment]
> I've started to work on v2 support (see `dev` branch), but it's not quite ready yet.
Hi there! Any chance this great workflow will be updated still, or should we consider it K.I.A.? 😬

**Comment by fniephaus** [comment]
@davidvb maybe give the version on [`dev`](https://github.com/fniephaus/alfred-dropbox/tree/dev) a try and file any issues. If that works ok, we can release it. Please note that Dropbox has changed a few things with their API v2, so some things are no longer supported (but I forgot which ones).
