### ISSUE TITLE
Doesn't function after auth...

### ISSUE THREAD

**Issue by ChausseBenjamin** [fniephaus/alfred-dropbox#8]
Starting debug for 'Dropbox for Alfred - COPY'

[2018-10-03 08:52:37][ERROR: input.scriptfilter] Code 1: 08:52:37 workflow.py:2249 DEBUG    workflow version: 2.3.0
08:52:37 workflow.py:1657 DEBUG    reading settings from /Users/Benjamin/Library/Application Support/Alfred 3/Workflow Data/com.fniephaus.dropbox/settings.json
08:52:37 workflow.py:2532 DEBUG    Update check not due
08:52:37 workflow.py:1884 DEBUG    loading cached data: /Users/Benjamin/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.fniephaus.dropbox/__workflow_update_status.cpickle
08:52:37 workflow.py:2462 DEBUG    update_data: {u'available': False}
08:52:37 workflow.py:2651 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
08:52:37 workflow.py:2651 DEBUG    Got password : com.fniephaus.dropbox:dropbox_access_tokens
08:52:37 workflow.py:2267 ERROR    [400] u'v1_retired'
Traceback (most recent call last):
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/workflow/workflow.py", line 2260, in run
    func(self)
  File "dropbox_filter.py", line 28, in main
    'dropbox_accounts', data_func=get_account_info, max_age=360)
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/helpers.py", line 40, in get_account_info
    output.append(api_client.account_info())
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/dropbox/client.py", line 149, in account_info
    return self.rest_client.GET(url, headers)
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/dropbox/rest.py", line 311, in GET
    return cls.IMPL.GET(*n, **kw)
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/dropbox/rest.py", line 246, in GET
    return self.request("GET", url, headers=headers, raw_response=raw_response)
  File "/Users/Benjamin/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.4A420B7A-3718-4454-AAF6-8A6EBB65ED2C/dropbox/rest.py", line 227, in request
    raise ErrorResponse(r, r.read())
ErrorResponse: [400] u'v1_retired'
08:52:37 workflow.py:2269 INFO     for assistance, see: https://github.com/fniephaus/alfred-dropbox/issues
08:52:37 workflow.py:2290 DEBUG    workflow finished in 0.375 seconds

**Comment by fniephaus** [comment]
Hi @ChausseBenjamin, I'm afraid this workflow does not work at the moment (see https://github.com/fniephaus/alfred-dropbox/issues/7#issuecomment-397060519).

**Comment by ChausseBenjamin** [comment]
Cool thanks!
